apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  LOGSTASH_HOST: "logstash"
  LOGSTASH_PORT: "5000"