apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notifications.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notifications.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: notifications
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: notifications-config
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 20