apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/certs"
  ACCOUNTS_URI: "http://accounts:8082"
  CASH_URI: "http://cash:8083"
  TRANSFER_URI: "http://transfer:8084"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  LOGSTASH_HOST: "logstash"
  LOGSTASH_PORT: "5000"