server:
  port: 8084

spring:
  application:
    name: transfer
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: transfer
            client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}
            authorization-grant-type: client_credentials
            scope: accounts.write
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/token}
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  accounts-url: ${APP_ACCOUNTS_URL:http://localhost:8082}
  kafka:
    notifications-topic: ${APP_KAFKA_NOTIFICATIONS_TOPIC:notifications}

logstash:
  host: ${LOGSTASH_HOST:localhost}
  port: ${LOGSTASH_PORT:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true