apiVersion: v1
kind: ConfigMap
metadata:
  name: cash-config
  labels:
    {{- include "cash.labels" . | nindent 4 }}
data:
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/certs"
  KEYCLOAK_TOKEN_URI: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/token"
  APP_ACCOUNTS_URL: "http://accounts:8082"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  LOGSTASH_HOST: "logstash"
  LOGSTASH_PORT: "5000"