apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash
  labels:
    {{- include "cash.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cash.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cash
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: cash-config
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: cash-client-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 20