server:
  port: 8080

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/certs}
  cloud:
    gateway:
      server:
        webflux:
          trusted-proxies: ".*"
          routes:
            - id: accounts
              uri: ${ACCOUNTS_URI:http://localhost:8082}
              predicates:
                - Path=/api/accounts/**
              filters:
                - TokenRelay=
                - name: CircuitBreaker
                  args:
                    name: accounts
                    fallbackUri: forward:/fallback

            - id: cash
              uri: ${CASH_URI:http://localhost:8083}
              predicates:
                - Path=/api/cash/**
              filters:
                - TokenRelay=
                - name: CircuitBreaker
                  args:
                    name: cash
                    fallbackUri: forward:/fallback

            - id: transfer
              uri: ${TRANSFER_URI:http://localhost:8084}
              predicates:
                - Path=/api/transfer/**
              filters:
                - TokenRelay=
                - name: CircuitBreaker
                  args:
                    name: transfer
                    fallbackUri: forward:/fallback

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

resilience4j:
  circuitbreaker:
    instances:
      accounts:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      cash:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      transfer:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s