apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "logstash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "logstash.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: logstash
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.tcpPort }}
              name: tcp
          env:
            - name: LS_JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: config
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: pipelines.yml
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.tcpPort }}
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.tcpPort }}
            initialDelaySeconds: 90
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: logstash-config
        - name: pipeline
          configMap:
            name: logstash-pipeline
