server:
  port: 8081

spring:
  application:
    name: front-ui
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: front-ui
            client-secret: ${KEYCLOAK_CLIENT_SECRET:front-ui-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email, accounts.read, accounts.write, cash.write, transfer.write
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/token}
            jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/certs}
            user-info-uri: ${KEYCLOAK_USER_INFO_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/userinfo}
            user-name-attribute: preferred_username

app:
  gateway-url: ${APP_GATEWAY_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true