secrets:
  postgresUser: postgres
  postgresPassword: postgres
  keycloakAdmin: admin
  keycloakAdminPassword: admin
  accountsClientSecret: accounts-secret
  cashClientSecret: cash-secret
  transferClientSecret: transfer-secret
  frontUiClientSecret: front-ui-secret

postgres:
  image:
    repository: postgres
    tag: "16-alpine"
  storage:
    size: 1Gi

kafka:
  image:
    repository: apache/kafka
    tag: "3.9.0"
  storage:
    size: 1Gi

zipkin:
  image:
    repository: openzipkin/zipkin
    tag: "3"
  service:
    type: NodePort
    port: 9411
    nodePort: 30411

prometheus:
  image:
    repository: prom/prometheus
    tag: "v3.0.1"
  service:
    type: NodePort
    port: 9090
    nodePort: 30909

keycloak:
  image:
    repository: quay.io/keycloak/keycloak
    tag: "26.0.0"
  service:
    type: NodePort
    port: 8080
    nodePort: 30180

accounts:
  image:
    repository: my-bank-accounts
    tag: latest

cash:
  image:
    repository: my-bank-cash
    tag: latest

transfer:
  image:
    repository: my-bank-transfer
    tag: latest

notifications:
  image:
    repository: my-bank-notifications
    tag: latest

gateway:
  image:
    repository: my-bank-gateway
    tag: latest

front-ui:
  image:
    repository: my-bank-front-ui
    tag: latest
  service:
    type: NodePort
    nodePort: 30081