apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-config
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
data:
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/certs"
  KEYCLOAK_TOKEN_URI: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/token"
  APP_ACCOUNTS_URL: "http://accounts:8082"
  APP_NOTIFICATIONS_URL: "http://notifications:8085"