apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "transfer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transfer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: transfer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: transfer-config
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: transfer-client-secret
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 20