apiVersion: v1
kind: Service
metadata:
  name: transfer
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "transfer.selectorLabels" . | nindent 4 }}