eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/my-bank/protocol/openid-connect/certs
