apiVersion: v1
kind: ConfigMap
metadata:
  name: front-ui-config
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
data:
  APP_GATEWAY_URL: "http://gateway:8080"
  KEYCLOAK_AUTHORIZATION_URI: "http://localhost:30180/realms/my-bank/protocol/openid-connect/auth"
  KEYCLOAK_TOKEN_URI: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/token"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/certs"
  KEYCLOAK_USER_INFO_URI: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/userinfo"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  LOGSTASH_HOST: "logstash"
  LOGSTASH_PORT: "5000"