apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ui
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "front-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: front-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: front-ui-config
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: front-ui-client-secret
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 20